name: Release and Build

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.1, v1.2.0, etc.

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Sync version from git tag
      run: node sync-version-from-git.js
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build-react

    - name: Copy React build to Electron
      run: npm run copy-react
      
    - name: Build Electron app (without publishing)
      run: npx electron-builder --publish never
      env:
        # Disable electron-builder auto-publishing
        CI: false
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Create zip package
      run: |
        Compress-Archive -Path "dist/win-unpacked/*" -DestinationPath "Office-or-Home-Office-v${{ steps.get_version.outputs.VERSION }}.zip"
      shell: powershell
      
    - name: Create Release with GitHub CLI
      run: |
        gh release create ${{ github.ref_name }} `
          "Office-or-Home-Office-v${{ steps.get_version.outputs.VERSION }}.zip" `
          --title "Version ${{ steps.get_version.outputs.VERSION }}" `
          --notes "## What's New in Version ${{ steps.get_version.outputs.VERSION }}

        - Auto-generated release
        - Download the zip file below and extract to use the app
        - Existing users will be notified automatically

        ## Installation
        1. Download ``Office-or-Home-Office-v${{ steps.get_version.outputs.VERSION }}.zip``
        2. Extract the zip file
        3. Run ``Office or Home Office.exe``"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: powershell
